### ISSUE TITLE
Group similar styles to optimize CSS

### ISSUE THREAD

**Issue by kyrose** [courtneypure/courtneypure.github.io#4]
Group `h1`, `h2`, and `h3` headings' [shared styles](https://github.com/courtneypure/courtneypure.github.io/blob/1bc212c426885413ba7a6b18e7340f3b4fb1115e/css/style.css#L21-L40) to reduce the size of your CSS files for optimized loading times.

```css
h1, h2, h3 {
  font-weight: 200;
  text-align: center;
  text-transform: uppercase;
}

h1 {
  font-size: 3em;
}

h2 {
  font-size: 2em;
}

h3 {
  font-size: 1em;
}

**Comment by kyrose** [comment]
Another instance! This one isn't quite as obvious: the [floated columns rulesets](https://github.com/courtneypure/courtneypure.github.io/blob/1bc212c426885413ba7a6b18e7340f3b4fb1115e/css/style.css#L139-L156) can be grouped together by their values for `float`:

```css
.courtney,
.demo-reel-artwork {
  float: left;
}

.about-type,
.demo-type {
  float: right;
}
```
